events {

}
http {  
    access_log  /var/log/nginx/access.log;
    server { 
        listen 443 ssl;
        ssl_certificate     /etc/ssl/certs/server.crt;
        ssl_certificate_key /etc/ssl/private/server.key;
        
        location / {

            # Hack to override discovery 
            sub_filter_types   application/json;
            sub_filter 'https://b3130a55.databases.neo4j.io/'  'https://database.haklof.corp/';

            # Proxy pass to db
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass https://b3130a55.databases.neo4j.io/;
            proxy_ssl_server_name on;
        }
    }
}






